"""auto_20260617_111013

Revision ID: bb2d26c4951b
Revises: b721a6ea6d18
Create Date: 2026-06-17 11:10:13.287526

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb2d26c4951b'
down_revision: Union[str, None] = 'b721a6ea6d18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('placement_done', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'placement_done')
    # ### end Alembic commands ###
