"""앱 기동 시 Alembic 스키마 자동 동기화.

흐름 (_sync_migrate):
1. upgrade head   — 커밋된 미적용 리비전 파일 먼저 적용
2. check          — 현재 모델 vs DB 스키마 드리프트 감지
3. 드리프트 있으면 revision --autogenerate + upgrade head 재실행

env.py 충돌 주의:
  alembic/env.py 의 run_migrations_online() 은 asyncio.run() 을 내부 호출한다.
  FastAPI lifespan 은 이미 이벤트 루프 안에 있으므로, 이 함수는
  asyncio.to_thread() 로 새 스레드에 위임해야 중첩 루프 오류가 발생하지 않는다.
"""

from __future__ import annotations

import asyncio
from datetime import datetime
from pathlib import Path

from alembic import command
from alembic.config import Config
from alembic.util.exc import AutogenerateDiffsDetected

from app.core.logging import get_logger

logger = get_logger(__name__)

# alembic.ini 가 있는 backend/ 루트 경로
_BACKEND_DIR = Path(__file__).parent.parent.parent


def _get_cfg() -> Config:
    # alembic.ini 위치와 script_location 을 절대 경로로 고정
    cfg = Config(str(_BACKEND_DIR / "alembic.ini"))
    cfg.set_main_option("script_location", str(_BACKEND_DIR / "alembic"))
    return cfg


def _sync_migrate() -> None:
    """동기 함수 — 스레드 내에서 실행되어야 한다."""
    cfg = _get_cfg()

    # 1) 기존 커밋된 미적용 리비전 먼저 적용
    logger.info("마이그레이션 적용 중 (upgrade head)...")
    command.upgrade(cfg, "head")

    # 2) 현재 모델 vs DB 스키마 차이 확인
    # command.check() 는 변경 없을 때 sys.exit(0) 을 호출 → SystemExit(0) 을 정상으로 처리
    try:
        command.check(cfg)
        logger.info("스키마 동기화 완료 — 변경 없음")
    except SystemExit as exc:
        if exc.code == 0:
            logger.info("스키마 동기화 완료 — 변경 없음")
        else:
            raise
    except AutogenerateDiffsDetected:
        # 3) 드리프트 감지 — 타임스탬프 이름으로 리비전 자동 생성 후 적용
        ts = datetime.now().strftime("%Y%m%d_%H%M%S")
        logger.info("스키마 변경 감지 — 리비전 자동 생성: auto_%s", ts)
        command.revision(cfg, autogenerate=True, message=f"auto_{ts}")
        command.upgrade(cfg, "head")
        logger.info("자동 마이그레이션 완료")


async def run_migrations() -> None:
    """비동기 lifespan 에서 호출하는 진입점.

    asyncio.to_thread() 로 격리해 env.py 의 asyncio.run() 이
    별도 스레드에서 새 이벤트 루프를 생성할 수 있도록 한다.
    """
    await asyncio.to_thread(_sync_migrate)
